### PR TITLE
Fixed crash related with 7TV animated pfp

### LINKED ISSUE #84: Chatterino keeps crashing
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [x] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [x] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

If you click on someone's profile and close it before the 7tv animated pfp loads chatterino just crashes 

### Screenshots

_No response_

### OS and Chatterino Version

Chatterino 7.3.5 (commit 132b406cc)

### PR DESCRIPTION
**Pull request by itzAlex**
Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable

# Description

This PR fixes a crash that occurs when you open someone's usercard and close it before the 7TV pfp is loaded. Closes #84

### CODE REVIEW

File: src/widgets/dialogs/UserInfoPopup.cpp [hunk 1]
```diff
@@ -1007,7 +1006,13 @@ void UserInfoPopup::fetchSevenTVAvatar(const HelixUser &user)
...
 
                         this->saveCacheAvatar(data, filename);
-                        this->setSevenTVAvatar(filename);
+
+                        bool hasFocus = (QApplication::focusWidget() == nullptr);
+                        if (hasFocus)
+                        {
+                            this->avatarUrl_ = URI;
+                            this->setSevenTVAvatar(filename);
+                        }
```
Comment (jupjohn) [inline src/widgets/dialogs/UserInfoPopup.cpp]: `QApplication::focusWidget()` may not have the intended behaviour on all platforms (at least not for me). Instead, a `nullptr` check on the avatar button itself would be better as the button will be a  `nullptr` when closed.
```suggestion
                        if (this->ui_.avatarButton != nullptr)
                        {
                            this->avatarUrl_ = URI;
                            this->setSevenTVAvatar(filename);
                        }
```

**Review by jupjohn — CHANGES_REQUESTED** [review]
This change completely breaks animated profile pictures for me as shown by opening ALazyMeme's usercard on your branch:

image

I believe this fix only works on Windows (or whatever OS you're using) so I've suggested a change.

File: src/widgets/dialogs/UserInfoPopup.cpp (hunk 1 above)
Comment (TroyKomodo) [reply src/widgets/dialogs/UserInfoPopup.cpp]: I agree.

Comment (itzAlex) [reply src/widgets/dialogs/UserInfoPopup.cpp]: I tested my branch on Windows and Arch (https://streamable.com/e/f5y3ke) and it seemed to work fine. However your fix is much better. Thank you very much! :)

Comment (jupjohn) [reply src/widgets/dialogs/UserInfoPopup.cpp]: I'm assuming it was a WM-related issue

**Review by jupjohn — APPROVED** [review]
LGTM!
